name: Build toolchain

on:
  push:
    branches:
      - main

env:
  LLVM_VERSION: 18
  NINJA_VERSION: 1.12.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=llvm${{ env.LLVM_VERSION }}-ninja${{ env.NINJA_VERSION }}

      - name: Login to GitHub repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64
          build-args: |
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            NINJA_VERSION=${{ env.NINJA_VERSION }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
