name: Build toolchain

on:
  push:
    branches:
      - main

env:
  LLVM_VERSION: 18
  NINJA_VERSION: 1.12.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set ninja filename
        id: ninja-filename
        run: echo 'name=ninja-linux.zip' >> $GITHUB_OUTPUT

      - name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup image name
        id: image
        run: |
          echo "name=ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Setup Metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ steps.image.outputs.name }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=llvm${{ env.LLVM_VERSION }}-ninja${{ env.NINJA_VERSION }}

      - name: Build image
        uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          context: .
          build-args: |
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            NINJA_VERSION=${{ env.NINJA_VERSION }}
            NINJA_FILENAME=${{ steps.ninja-filename.outputs.name }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
