name: Build toolchain

on:
  push:
    branches:
      - main

env:
  LLVM_VERSION: 18
  NINJA_VERSION: 1.12.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set ninja filename
        id: ninja-filename
        run: |
          if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
            echo 'name=ninja-linux.zip' >> $GITHUB_OUTPUT
          else
            echo 'name=ninja-linux-aarch64.zip' >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=raw,value=llvm${{ env.LLVM_VERSION }}-ninja${{ env.NINJA_VERSION }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            NINJA_VERSION=${{ env.NINJA_VERSION }}
            NINJA_FILENAME=${{ steps.ninja-filename.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
